[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer", "@netlify/blobs"]

# Optional: shortcut so /inbound works too
[[redirects]]
  from = "/inbound"
  to = "/.netlify/functions/inbound"
  status = 200
  force = true