[build]
  # directory for your static site (adjust if your index.html is somewhere else)
  publish = "."
  # where your serverless functions are
  functions = "netlify/functions"

[functions]
  # optionally set a Node.js runtime version
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer", "mailparser"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200