[build]
  # Serve static files from the project root
  publish = "."
  # Directory where your Netlify Functions live
  functions = "netlify/functions"

[functions]
  # Use esbuild for bundling
  node_bundler = "esbuild"
  # Make sure these modules are bundled (needed for send-email + inbound logging)
  external_node_modules = ["nodemailer", "@netlify/blobs"]

# Optional but useful: allows you to POST directly to /inbound
[[redirects]]
  from = "/inbound"
  to = "/.netlify/functions/inbound"
  status = 200
  force = true

# You can add more redirects for other functions if you like:
# e.g. send-email and thread
[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

[[redirects]]
  from = "/thread"
  to = "/.netlify/functions/thread"
  status = 200
  force = true